version: 2.1
orbs:
  anima-orb: anima/anima-orb@dev:alpha
workflows:
  scooby:
    jobs:
      - build-and-test
      - run-scooby-regression-tests
      - run-scooby-fidelity-tests
      - run-scooby-fidelity-regression-tests
      - scooby-update-status:
          requires:
            - run-scooby-regression-tests
            - run-scooby-fidelity-tests
            - run-scooby-fidelity-regression-tests

      - deploy-scooby-web-ui:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main

      - request-npm-packages-deploy-approval:
          type: approval
          requires:
            - build-and-test
          filters:
            branches:
              only: main
      - deploy-npm-packages:
          context: anima-prod
          requires:
            - request-npm-packages-deploy-approval
          filters:
            branches:
              only: main

  web-service:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - anima-orb/build-push-image:
          context: anima-prod
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
      - anima-orb/update-argocd-repo:
          context: anima-prod
          cluster-name: anima-cluster
          requires:
            - anima-orb/build-push-image
          filters:
            branches:
              only: main
jobs:
  build-and-test:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - run:
          name: "Build monorepo"
          command: "yarn build:all"
      - run:
          name: "Run tests"
          command: "./scripts/run_all_tests.sh"
      - run:
          name: "Check formatting"
          command: "yarn check:format"

  run-scooby-regression-tests:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - setup-scooby
      - run:
          name: "Run HTML regression test"
          command: "scooby regression --name 'html-regression' --tests sample-projects/ci-html-regression --file-type=html"
      - run:
          name: "Run HTML code regression test"
          command: "scooby regression --name 'html-code-regression' --tests sample-projects/ci-html-code-regression --file-type=html,css --dataset-type=code"
      - run:
          name: "Run PNG regression test"
          command: "scooby regression --name 'png-regression' --tests sample-projects/ci-png-regression --file-type=png"
      - run:
          name: "Run JSON regression test"
          command: "scooby regression --name 'json-regression' --tests sample-projects/ci-json-regression --file-type=json"
      - run:
          name: "Run JSX regression test"
          command: "scooby regression --name 'jsx-regression' --tests sample-projects/ci-jsx-regression --file-type=jsx"
      - run:
          name: "Run Recursive HTML regression test"
          command: "scooby regression --name 'recursive-html-regression' --tests sample-projects/ci-recursive-regression --file-type=html"
      - run:
          name: "Run JSON regression (with metadata) test"
          command: "scooby regression --name 'json-regression-with-metadata' --tests sample-projects/ci-json-regression-metadata --file-type=json"
      - run:
          name: "Run regression test with ZIP output target"
          command: "scooby regression --name 'zip-png-regression' --tests sample-projects/ci-png-regression --file-type=png --output=zip"
      - run:
          name: "Run JSX regression test with mixed file types"
          command: "scooby regression --name 'jsx-regression' --tests sample-projects/ci-jsx-regression --file-type=jsx,css"

  run-scooby-fidelity-tests:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - setup-scooby
      - run:
          name: "Run HTML fidelity test"
          command: "scooby fidelity --name 'html-fidelity' --expected sample-projects/ci-html-fidelity/expected --actual sample-projects/ci-html-fidelity/actual --threshold=0.5 --file-type=html"
      - run:
          name: "Run JSON fidelity test"
          command: "scooby fidelity --name 'json-fidelity' --expected sample-projects/ci-json-fidelity/expected --actual sample-projects/ci-json-fidelity/actual --file-type=json"
      - run:
          name: "Run JSX fidelity test"
          command: "scooby fidelity --name 'jsx-fidelity' --expected sample-projects/ci-jsx-fidelity/expected --actual sample-projects/ci-jsx-fidelity/actual --file-type=jsx"
      - run:
          name: "Run nested JSX fidelity test"
          command: "scooby fidelity --name 'nested-jsx-fidelity' --expected sample-projects/ci-nested-jsx-fidelity/expected --actual sample-projects/ci-nested-jsx-fidelity/actual --file-type=jsx"
      - run:
          name: "Run HTML fidelity (with-metadata) test"
          command: "scooby fidelity --name 'html-fidelity-metadata' --expected sample-projects/ci-html-fidelity-metadata/expected --actual sample-projects/ci-html-fidelity-metadata/actual --threshold=0.5 --file-type=html"
      - run:
          name: "Run mixed file-type fidelity test"
          command: "scooby fidelity --name 'mixed-file-type-fidelity' --expected sample-projects/ci-mixed-fidelity/expected --actual sample-projects/ci-mixed-fidelity/actual --expected-file-type=png --actual-file-type=html"
      - run:
          name: "Run fidelity test with ZIP output target"
          command: "scooby fidelity --name 'zip-json-fidelity' --expected sample-projects/ci-json-fidelity/expected --actual sample-projects/ci-json-fidelity/actual --file-type=json --output=zip"
      - run:
          name: "Run JSX fidelity test with multiple format types"
          command: "scooby fidelity --name 'jsx-fidelity-mixed' --expected sample-projects/ci-jsx-fidelity-mixed/expected --actual sample-projects/ci-jsx-fidelity-mixed/actual --file-type=jsx,css"

  run-scooby-fidelity-regression-tests:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - setup-scooby
      - run:
          name: "Run HTML fidelity regression test"
          command: "scooby fidelity-regression --name 'html-fidelity-regression' --expected sample-projects/ci-html-fidelity/expected --actual sample-projects/ci-html-fidelity/actual --file-type=html"
      - run:
          name: "Run JSON fidelity regression test"
          command: "scooby fidelity-regression --name 'json-fidelity-regression' --expected sample-projects/ci-json-fidelity/expected --actual sample-projects/ci-json-fidelity/actual --file-type=json"
      - run:
          name: "Run JSX fidelity regression test"
          command: "scooby fidelity-regression --name 'jsx-fidelity-regression' --expected sample-projects/ci-jsx-fidelity/expected --actual sample-projects/ci-jsx-fidelity/actual --file-type=jsx"
      - run:
          name: "Run nested JSX fidelity regression test"
          command: "scooby fidelity-regression --name 'nested-jsx-fidelity-regression' --expected sample-projects/ci-nested-jsx-fidelity/expected --actual sample-projects/ci-nested-jsx-fidelity/actual --file-type=jsx"
      - run:
          name: "Run HTML fidelity regression (with-metadata) test"
          command: "scooby fidelity-regression --name 'html-fidelity-regression-metadata' --expected sample-projects/ci-html-fidelity-metadata/expected --actual sample-projects/ci-html-fidelity-metadata/actual --file-type=html"
      - run:
          name: "Run mixed file-type fidelity regression test"
          command: "scooby fidelity-regression --name 'mixed-file-type-fidelity-regression' --expected sample-projects/ci-mixed-fidelity/expected --actual sample-projects/ci-mixed-fidelity/actual --expected-file-type=png --actual-file-type=html"
      - run:
          name: "Run fidelity regression test with ZIP output target"
          command: "scooby fidelity-regression --name 'zip-json-fidelity-regression' --expected sample-projects/ci-json-fidelity/expected --actual sample-projects/ci-json-fidelity/actual --file-type=json --output=zip"
      - run:
          name: "Run fidelity regression test with images and flexible matching"
          command: "scooby fidelity-regression --name 'html-fidelity-regression-shared-images' --expected sample-projects/ci-html-fidelity-regression-shared-images/expected --expected-file-type=png --actual sample-projects/ci-html-fidelity-regression-shared-images/actual --actual-file-type=html --fidelity-matching=flexible"
      - run:
          name: "Run JSX fidelity regression test with mixed file types"
          command: "scooby fidelity-regression --name 'jsx-fidelity-regression-mixed' --expected sample-projects/ci-jsx-fidelity-mixed/expected --actual sample-projects/ci-jsx-fidelity-mixed/actual --file-type=jsx,css"

  scooby-update-status:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - setup-scooby
      - run:
          name: "Update GitHub status"
          command: "scooby update-status"

  deploy-scooby-web-ui:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - run:
          name: "Build Scooby Web"
          command: "yarn web build"
      - run:
          name: Install deploy dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@animaapp.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ed:65:07:95:99:35:d0:fb:3c:38:82:39:db:2a:98:ee"
      - run:
          name: "Add Jekyll disable file"
          command: "touch ./packages/scooby-web/dist/.nojekyll"
      - run:
          name: Deploy Scooby Web to gh-pages branch
          command: gh-pages --dotfiles --message '[skip ci] updates' --dist ./packages/scooby-web/dist

  deploy-npm-packages:
    docker:
      - image: node:16
    steps:
      - run:
          name: Set npm registry
          command: |
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
            echo "@animaapp:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=\${GITHUB_PACKAGE_TOKEN}" >> ~/.npmrc
      - setup-dependencies
      - add_ssh_keys:
          fingerprints:
            - "ed:65:07:95:99:35:d0:fb:3c:38:82:39:db:2a:98:ee"
      - run:
          name: "Setting up bot account for PR creation"
          command: |
            git config user.email "federico+ci_bot@animaapp.com"
            git config user.name "Anima CI Bot"
      - run:
          name: "Preparing repo for package publish"
          command: |
            git checkout -b "chore/release-$CIRCLE_WORKFLOW_JOB_ID"
            git push --set-upstream origin "chore/release-$CIRCLE_WORKFLOW_JOB_ID"
      - run:
          name: "Build monorepo"
          command: "yarn build:all"

      # Publish on GitHub NPM registry
      - run:
          name: "Preparing packages"
          command: "yarn release:prepare:ci"
      - run:
          name: "Publishing to GitHub NPM registry"
          command: "yarn release:publish:ci"

      - run:
          name: "Creating PR"
          command: |
            git push
            BRANCH_ID="chore/release-$CIRCLE_WORKFLOW_JOB_ID"
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $SCOOBY_GITHUB_CI_BOT_TOKEN" \
              "https://api.github.com/repos/AnimaApp/scooby/pulls" \
              -d "{\"title\":\"chore: release\",\"body\":\"Package release automatically generated by CI\",\"head\":\"$BRANCH_ID\",\"base\":\"main\"}"

      # Publish on public NPM registry
      - run:
          name: "Publishing to public NPM registry"
          command: |
            # Patching the NPMRC entry so that we push all packages to the public NPM registry instead of the Github NPM registry
            echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > ~/.npmrc

            ./scripts/publish_to_public_npm_registry.sh

  patch-request-npm-packages-deploy-approval-github-status:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: "Install Ubuntu dependencies"
          command: |
            apt-get -y update
            apt-get install -y jq curl
      - run:
          name: "Patching Approval status"
          command: |
            ./scripts/patch_pending_circleci_approval.sh "scooby/request-npm-packages-deploy-approval"

commands:
  setup-dependencies:
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "yarn install --frozen-lockfile"
      - run:
          name: "Install Ubuntu dependencies"
          command: |
            apt-get -y update
            apt-get install -y libasound2 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev chromium jq curl rsync

  setup-scooby:
    steps:
      - run:
          name: "Build Scooby CLI"
          command: "yarn cli build"
      - run:
          name: "Setup snoopy alias"
          command: |
            ln -s $(pwd)/packages/scooby-cli/bin/run /usr/bin/scooby

# VS Code Extension Version: 1.5.0
