version: 2.1
orbs:
  anima-orb: anima/anima-orb@dev:alpha
workflows:
  scooby:
    jobs:
      - build-and-test:
          context: anima-prod

      - run-scooby-regression-tests:
          context: anima-prod

      - deploy-scooby-web-ui:
          context: anima-prod
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
jobs:
  build-and-test:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - run:
          name: "Build monorepo"
          command: "yarn build:all"
      - run:
          name: "Run tests"
          command: "./scripts/run_all_tests.sh"
      - run:
          name: "Check formatting"
          command: "yarn check:format"

  run-scooby-regression-tests:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - run:
          name: "Build Scooby CLI"
          command: "yarn cli build"
      - run:
          name: "Run HTML regression test"
          command: "./packages/scooby-cli/bin/run regression --name 'html-regression' --tests sample-projects/ci-html-regression"

  deploy-scooby-web-ui:
    docker:
      - image: node:16
    steps:
      - setup-dependencies
      - run:
          name: "Build Scooby Web"
          command: "yarn web build"
      - run:
          name: Install deploy dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@animaapp.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ed:65:07:95:99:35:d0:fb:3c:38:82:39:db:2a:98:ee"
      - run:
          name: "Add Jekyll disable file"
          command: "touch ./packages/scooby-web/dist/.nojekyll"
      - run:
          name: Deploy Scooby Web to gh-pages branch
          command: gh-pages --dotfiles --message '[skip ci] updates' --dist ./packages/scooby-web/dist

commands:
  setup-dependencies:
    steps:
      - run:
          name: Set npm registry
          command: |
            echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
            echo "@animaapp:registry=https://npm.pkg.github.com/" >> ~/.npmrc
            echo "//npm.pkg.github.com/:_authToken=\${GITHUB_PACKAGE_TOKEN}" >> ~/.npmrc
      - checkout
      - run:
          name: "Install dependencies"
          command: "yarn install --frozen-lockfile"
      - run:
          name: "Install Ubuntu dependencies"
          command: |
            apt-get -y update
            apt-get install -y libasound2 libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev chromium jq curl rsync
